/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Agenda } from "./Agenda";
import { AgendaCountArgs } from "./AgendaCountArgs";
import { AgendaFindManyArgs } from "./AgendaFindManyArgs";
import { AgendaFindUniqueArgs } from "./AgendaFindUniqueArgs";
import { CreateAgendaArgs } from "./CreateAgendaArgs";
import { UpdateAgendaArgs } from "./UpdateAgendaArgs";
import { DeleteAgendaArgs } from "./DeleteAgendaArgs";
import { AgendaService } from "../agenda.service";
@graphql.Resolver(() => Agenda)
export class AgendaResolverBase {
  constructor(protected readonly service: AgendaService) {}

  async _agendaItemsMeta(
    @graphql.Args() args: AgendaCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Agenda])
  async agendaItems(
    @graphql.Args() args: AgendaFindManyArgs
  ): Promise<Agenda[]> {
    return this.service.agendaItems(args);
  }

  @graphql.Query(() => Agenda, { nullable: true })
  async agenda(
    @graphql.Args() args: AgendaFindUniqueArgs
  ): Promise<Agenda | null> {
    const result = await this.service.agenda(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Agenda)
  async createAgenda(@graphql.Args() args: CreateAgendaArgs): Promise<Agenda> {
    return await this.service.createAgenda({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Agenda)
  async updateAgenda(
    @graphql.Args() args: UpdateAgendaArgs
  ): Promise<Agenda | null> {
    try {
      return await this.service.updateAgenda({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Agenda)
  async deleteAgenda(
    @graphql.Args() args: DeleteAgendaArgs
  ): Promise<Agenda | null> {
    try {
      return await this.service.deleteAgenda(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
